### ISSUE TITLE
rsPackageSourceManager

### ISSUE THREAD

**Issue by mkey0bc** [rsWinAutomationSupport/rsPackageSourceManager#13]
Bug preventing bootstrap automation. Error from logs.

Log Name:      Microsoft-Windows-DSC/Operational
Source:        Microsoft-Windows-DSC
Date:          9/3/2015 8:28:10 PM
Event ID:      4103
Task Category: None
Level:         Error
Keywords:  
User:          SYSTEM
Computer:      WIN-P02EVLL4KM5
Description:
Job {46262197-527A-11E5-8102-061317EB4E51} : 
This event indicates that a non-terminating error was thrown when DSCEngine was executing Test-TargetResource on RS_rsGit DSC resource. FullyQualifiedErrorId is CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand. ErrorMessage is The term 'git.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again..
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-DSC" Guid="{50DF9E12-A8C4-4939-B281-47E1325BA63E}" />
    <EventID>4103</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2015-09-03T20:28:10.262282700Z" />
    <EventRecordID>9</EventRecordID>
    <Correlation ActivityID="{2BB20EA8-E686-0000-C11A-B22B86E6D001}" />
    <Execution ProcessID="1968" ThreadID="1980" />
    <Channel>Microsoft-Windows-DSC/Operational</Channel>
    <Computer>WIN-P02EVLL4KM5</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="JobId">{46262197-527A-11E5-8102-061317EB4E51}</Data>
    <Data Name="ComponentName">DSCEngine</Data>
    <Data Name="OperationCmd">Test-TargetResource</Data>
    <Data Name="ProviderName">RS_rsGit</Data>
    <Data Name="FullyQualifiedErrorId">CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand</Data>
    <Data Name="ErrorMessage">The term 'git.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.</Data>
  </EventData>
</Event>

**Comment by leshkinski** [comment]
Closing this - fixed with referenced commit
