### ISSUE TITLE
Typo in parameter type for test and set in rsModuleZipSum 

### ISSUE THREAD

**Issue by leshkinski** [rsWinAutomationSupport/rsPackageSourceManager#3]
Parameter type for $modulePath variable in Test and Set functions in rsModuleZipSum resource is being set to "[strin]" and is currently an issue in master and staging branches.

Causes the following error if being used:
`Unable to find type [strin]. Make sure that the assembly that contains this type is loaded.`

**Comment by horacio3** [comment]
Already fixed in Universal and wmf4 branches. Just need to be merged into staging and master

**Comment by mkey0bc** [comment]
This bug was fixed in commit 00d6ccfa2cd4935ca525f92b02b0dfca0638637a on March 10th on the universal branch. Once this branch is tested and approved then we can merge it to staging and master then tag it for production.

**Comment by leshkinski** [comment]
Shouldn't we keep an issue open until the fix is merged into master, at least for visibility?
